# Generated by Django 4.1.7 on 2023-11-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ears_shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('photo', models.ImageField(upload_to='ears_shape')),
            ],
        ),
        migrations.CreateModel(
            name='Eyebrows_shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('photo', models.ImageField(upload_to='eyebrows_shape')),
            ],
        ),
        migrations.CreateModel(
            name='Eyes_shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('photo', models.ImageField(upload_to='eyes_shape')),
            ],
        ),
        migrations.CreateModel(
            name='Face_shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('photo', models.ImageField(upload_to='face_shape')),
            ],
        ),
        migrations.CreateModel(
            name='Hair_style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('photo', models.ImageField(upload_to='hair_style')),
            ],
        ),
        migrations.CreateModel(
            name='lips_shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('photo', models.ImageField(upload_to='lips_shape')),
            ],
        ),
        migrations.CreateModel(
            name='Nose_shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('photo', models.ImageField(upload_to='nose_shape')),
            ],
        ),
    ]
