# Generated by Django 4.1.7 on 2024-01-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facialcomposite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ears_shape',
            name='description',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eyebrows_shape',
            name='description',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eyes_shape',
            name='description',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='face_shape',
            name='description',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hair_style',
            name='description',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lips_shape',
            name='description',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nose_shape',
            name='description',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
