# Generated by Django 4.1.7 on 2024-01-02 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facialcomposite', '0002_ears_shape_description_eyebrows_shape_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_category', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='facial_feature',
            fields=[
                ('feature_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('feature_description', models.CharField(max_length=128)),
                ('feature_photo', models.ImageField(upload_to='facial_feature')),
                ('feature_name', models.CharField(max_length=128)),
                ('feature_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facialcomposite.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Ears_shape',
        ),
        migrations.DeleteModel(
            name='Eyebrows_shape',
        ),
        migrations.DeleteModel(
            name='Eyes_shape',
        ),
        migrations.DeleteModel(
            name='Face_shape',
        ),
        migrations.DeleteModel(
            name='Hair_style',
        ),
        migrations.DeleteModel(
            name='lips_shape',
        ),
        migrations.DeleteModel(
            name='Nose_shape',
        ),
    ]
