# Generated by Django 5.0.2 on 2024-02-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facialcomposite', '0003_category_facial_feature_delete_ears_shape_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='criminals',
            fields=[
                ('criminal_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('criminal_name', models.CharField(max_length=128)),
                ('criminal_age', models.IntegerField()),
                ('criminal_crime', models.CharField(max_length=1024)),
                ('criminal_mugshot', models.ImageField(upload_to='criminal_mugshot')),
            ],
        ),
    ]
