# Generated by Django 5.0.2 on 2024-02-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facialcomposite', '0004_criminals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminals',
            name='criminal_mugshot',
            field=models.ImageField(upload_to='criminal\\criminal_mugshot'),
        ),
    ]
